# references:
# * https://www.objc.io/issues/6-build-tools/travis-ci/
# * https://github.com/supermarin/xcpretty#usage

language: objective-c
osx_image: xcode10.2
branches:
  only:
    - master
env:
  global:
  - LC_CTYPE=en_US.UTF-8
  - LANG=en_US.UTF-8
  - WORKSPACE=Example/SmarterStreaming.xcworkspace
  - EXAMPLE_SCHEME="SmarterStreaming-Example"
  - PLAYER_SCHEME="SmartiOSPlayerV2"
  matrix:
    - DESTINATION="OS=9.3,name=iPhone 5"
    - DESTINATION="OS=10.3.1,name=iPhone 6"
    - DESTINATION="OS=11.4,name=iPhone 7 Plus"
    - DESTINATION="OS=12.2,name=iPhone X"
cache: cocoapods
podfile: Example/Podfile
before_install:
  - gem install cocoapods
  - pod install --project-directory=Example
script:
  - set -o pipefail
  - xcodebuild -version
  - xcodebuild -showsdks
  - xcodebuild clean build -workspace "$WORKSPACE" -scheme "$EXAMPLE_SCHEME" -destination "$DESTINATION" -sdk iphonesimulator -configuration Release ONLY_ACTIVE_ARCH=NO | xcpretty
  - pod lib lint